countries = [{
  'country': 'USA',
  'total_cases': 142793,
  'new_cases': 333,
  'total_deaths': 2490,
  'new_deaths': 6,
  'total_recovered': 4562,
  'active_cases': 135741,
  'serious_cases': 2970
}, {
  'country': 'Italy',
  'total_cases': 97689,
  'total_deaths': 10779,
  'total_recovered': 13030,
  'active_cases': 73880,
  'serious_cases': 3906
}, {
  'country': 'Spain',
  'total_cases': 85195,
  'new_cases': 5085,
  'total_deaths': 7340,
  'new_deaths': 537,
  'total_recovered': 16780,
  'active_cases': 61075,
  'serious_cases': 5231
}, {
  'country': 'Germany',
  'total_cases': 62435,
  'total_deaths': 541,
  'total_recovered': 9211,
  'active_cases': 52683,
  'serious_cases': 1979
}, {
  'country': 'Iran',
  'total_cases': 41495,
  'new_cases': 3186,
  'total_deaths': 2757,
  'new_deaths': 117,
  'total_recovered': 13911,
  'active_cases': 24827,
  'serious_cases': 3511
}, {
  'country': 'France',
  'total_cases': 40174,
  'total_deaths': 2606,
  'total_recovered': 7202,
  'active_cases': 30366,
  'serious_cases': 4632
}, {
  'country': 'UK',
  'total_cases': 19522,
  'total_deaths': 1228,
  'total_recovered': 135,
  'active_cases': 18159,
  'serious_cases': 163
}, {
  'country': 'Switzerland',
  'total_cases': 15475,
  'new_cases': 646,
  'total_deaths': 327,
  'new_deaths': 27,
  'total_recovered': 1823,
  'active_cases': 13325,
  'serious_cases': 301
}, {
  'country': 'Belgium',
  'total_cases': 11899,
  'new_cases': 1063,
  'total_deaths': 513,
  'new_deaths': 82,
  'total_recovered': 1527,
  'active_cases': 9859,
  'serious_cases': 927
}, {
  'country': 'Netherlands',
  'total_cases': 11750,
  'new_cases': 884,
  'total_deaths': 864,
  'new_deaths': 93,
  'total_recovered': 250,
  'active_cases': 10636,
  'serious_cases': 972
}, {
  'country': 'S. Korea',
  'total_cases': 9661,
  'new_cases': 78,
  'total_deaths': 158,
  'new_deaths': 6,
  'total_recovered': 5228,
  'active_cases': 4275,
  'serious_cases': 59
}, {
  'country': 'Turkey',
  'total_cases': 9217,
  'total_deaths': 131,
  'total_recovered': 105,
  'active_cases': 8981,
  'serious_cases': 568
}, {
  'country': 'Austria',
  'total_cases': 9200,
  'new_cases': 412,
  'total_deaths': 108,
  'new_deaths': 22,
  'total_recovered': 636,
  'active_cases': 8456,
  'serious_cases': 193
}, {
  'country': 'Portugal',
  'total_cases': 6408,
  'new_cases': 446,
  'total_deaths': 140,
  'new_deaths': 21,
  'total_recovered': 43,
  'active_cases': 6225,
  'serious_cases': 164
}, {
  'country': 'Canada',
  'total_cases': 6320,
  'total_deaths': 65,
  'total_recovered': 573,
  'active_cases': 5682,
  'serious_cases': 120
}, {
  'country': 'Norway',
  'total_cases': 4393,
  'new_cases': 109,
  'total_deaths': 31,
  'new_deaths': 5,
  'total_recovered': 12,
  'active_cases': 4350,
  'serious_cases': 97
}, {
  'country': 'Israel',
  'total_cases': 4347,
  'new_cases': 100,
  'total_deaths': 16,
  'new_deaths': 1,
  'total_recovered': 134,
  'active_cases': 4197,
  'serious_cases': 80
}, {
  'country': 'Brazil',
  'total_cases': 4316,
  'new_cases': 60,
  'total_deaths': 139,
  'new_deaths': 3,
  'total_recovered': 120,
  'active_cases': 4057,
  'serious_cases': 296
}, {
  'country': 'Australia',
  'total_cases': 4245,
  'new_cases': 82,
  'total_deaths': 18,
  'new_deaths': 1,
  'total_recovered': 244,
  'active_cases': 3983,
  'serious_cases': 28
}, {
  'country': 'Sweden',
  'total_cases': 3700,
  'total_deaths': 110,
  'total_recovered': 16,
  'active_cases': 3574,
  'serious_cases': 281
}, {
  'country': 'Czechia',
  'total_cases': 2866,
  'new_cases': 49,
  'total_deaths': 17,
  'new_deaths': 1,
  'total_recovered': 11,
  'active_cases': 2838,
  'serious_cases': 52
}, {
  'country': 'Malaysia',
  'total_cases': 2626,
  'new_cases': 156,
  'total_deaths': 37,
  'new_deaths': 2,
  'total_recovered': 479,
  'active_cases': 2110,
  'serious_cases': 94
}, {
  'country': 'Ireland',
  'total_cases': 2615,
  'total_deaths': 46,
  'total_recovered': 5,
  'active_cases': 2564,
  'serious_cases': 59
}, {
  'country': 'Denmark',
  'total_cases': 2555,
  'new_cases': 160,
  'total_deaths': 77,
  'new_deaths': 5,
  'total_recovered': 1,
  'active_cases': 2477,
  'serious_cases': 113
}, {
  'country': 'Chile',
  'total_cases': 2139,
  'total_deaths': 7,
  'total_recovered': 75,
  'active_cases': 2057,
  'serious_cases': 7
}, {
  'country': 'Romania',
  'total_cases': 1952,
  'new_cases': 137,
  'total_deaths': 46,
  'new_deaths': 3,
  'total_recovered': 206,
  'active_cases': 1700,
  'serious_cases': 31
}, {
  'country': 'Luxembourg',
  'total_cases': 1950,
  'total_deaths': 21,
  'total_recovered': 40,
  'active_cases': 1889,
  'serious_cases': 25
}, {
  'country': 'Ecuador',
  'total_cases': 1924,
  'total_deaths': 58,
  'total_recovered': 3,
  'active_cases': 1863,
  'serious_cases': 58
}, {
  'country': 'Poland',
  'total_cases': 1905,
  'new_cases': 43,
  'total_deaths': 26,
  'new_deaths': 4,
  'total_recovered': 7,
  'active_cases': 1872,
  'serious_cases': 3
}, {
  'country': 'Japan',
  'total_cases': 1866,
  'total_deaths': 54,
  'total_recovered': 424,
  'active_cases': 1388,
  'serious_cases': 56
}, {
  'country': 'Russia',
  'total_cases': 1836,
  'new_cases': 302,
  'total_deaths': 9,
  'new_deaths': 1,
  'total_recovered': 66,
  'active_cases': 1761,
  'serious_cases': 8
}, {
  'country': 'Pakistan',
  'total_cases': 1625,
  'new_cases': 28,
  'total_deaths': 20,
  'new_deaths': 6,
  'total_recovered': 29,
  'active_cases': 1576,
  'serious_cases': 11
}, {
  'country': 'Philippines',
  'total_cases': 1546,
  'new_cases': 128,
  'total_deaths': 78,
  'new_deaths': 7,
  'total_recovered': 42,
  'active_cases': 1426,
  'serious_cases': 1
}, {
  'country': 'Thailand',
  'total_cases': 1524,
  'new_cases': 136,
  'total_deaths': 9,
  'new_deaths': 2,
  'total_recovered': 229,
  'active_cases': 1286,
  'serious_cases': 11
}, {
  'country': 'Indonesia',
  'total_cases': 1414,
  'new_cases': 129,
  'total_deaths': 122,
  'new_deaths': 8,
  'total_recovered': 75,
  'active_cases': 1217
}, {
  'country': 'Finland',
  'total_cases': 1352,
  'new_cases': 112,
  'total_deaths': 13,
  'new_deaths': 2,
  'total_recovered': 10,
  'active_cases': 1329,
  'serious_cases': 32
}, {
  'country': 'Saudi Arabia',
  'total_cases': 1299,
  'total_deaths': 8,
  'total_recovered': 66,
  'active_cases': 1225,
  'serious_cases': 12
}, {
  'country': 'South Africa',
  'total_cases': 1280,
  'total_deaths': 2,
  'total_recovered': 31,
  'active_cases': 1247,
  'serious_cases': 7
}, {
  'country': 'Greece',
  'total_cases': 1156,
  'total_deaths': 39,
  'total_recovered': 52,
  'active_cases': 1065,
  'serious_cases': 66
}, {
  'country': 'India',
  'total_cases': 1071,
  'new_cases': 47,
  'total_deaths': 29,
  'new_deaths': 2,
  'total_recovered': 100,
  'active_cases': 942
}, {
  'country': 'Iceland',
  'total_cases': 1020,
  'total_deaths': 2,
  'total_recovered': 135,
  'active_cases': 883,
  'serious_cases': 25
}, {
  'country': 'Mexico',
  'total_cases': 993,
  'new_cases': 145,
  'total_deaths': 20,
  'new_deaths': 4,
  'total_recovered': 35,
  'active_cases': 938,
  'serious_cases': 1
}, {
  'country': 'Panama',
  'total_cases': 989,
  'total_deaths': 24,
  'total_recovered': 4,
  'active_cases': 961,
  'serious_cases': 36
}, {
  'country': 'Dominican Republic',
  'total_cases': 859,
  'total_deaths': 39,
  'total_recovered': 3,
  'active_cases': 817
}, {
  'country': 'Peru',
  'total_cases': 852,
  'total_deaths': 18,
  'total_recovered': 16,
  'active_cases': 818,
  'serious_cases': 40
}, {
  'country': 'Singapore',
  'total_cases': 844,
  'total_deaths': 3,
  'total_recovered': 212,
  'active_cases': 629,
  'serious_cases': 19
}, {
  'country': 'Argentina',
  'total_cases': 820,
  'total_deaths': 20,
  'total_recovered': 91,
  'active_cases': 709
}, {
  'country': 'Croatia',
  'total_cases': 790,
  'new_cases': 77,
  'total_deaths': 6,
  'total_recovered': 55,
  'active_cases': 729,
  'serious_cases': 26
}, {
  'country': 'Slovenia',
  'total_cases': 756,
  'new_cases': 26,
  'total_deaths': 11,
  'total_recovered': 10,
  'active_cases': 735,
  'serious_cases': 28
}, {
  'country': 'Serbia',
  'total_cases': 741,
  'total_deaths': 14,
  'new_deaths': 1,
  'total_recovered': 42,
  'active_cases': 685,
  'serious_cases': 25
}, {
  'country': 'Estonia',
  'total_cases': 715,
  'new_cases': 36,
  'total_deaths': 3,
  'total_recovered': 20,
  'active_cases': 692,
  'serious_cases': 10
}, {
  'country': 'Diamond Princess',
  'total_cases': 712,
  'total_deaths': 10,
  'total_recovered': 603,
  'active_cases': 99,
  'serious_cases': 15
}, {
  'country': 'Colombia',
  'total_cases': 702,
  'total_deaths': 10,
  'total_recovered': 10,
  'active_cases': 682,
  'serious_cases': 29
}, {
  'country': 'Hong Kong',
  'total_cases': 642,
  'total_deaths': 4,
  'total_recovered': 118,
  'active_cases': 520,
  'serious_cases': 5
}, {
  'country': 'Qatar',
  'total_cases': 634,
  'total_deaths': 1,
  'total_recovered': 48,
  'active_cases': 585,
  'serious_cases': 6
}, {
  'country': 'Egypt',
  'total_cases': 609,
  'total_deaths': 40,
  'total_recovered': 132,
  'active_cases': 437
}, {
  'country': 'New Zealand',
  'total_cases': 589,
  'new_cases': 75,
  'total_deaths': 1,
  'total_recovered': 63,
  'active_cases': 525,
  'serious_cases': 2
}, {
  'country': 'UAE',
  'total_cases': 570,
  'total_deaths': 3,
  'total_recovered': 58,
  'active_cases': 509,
  'serious_cases': 2
}, {
  'country': 'Iraq',
  'total_cases': 547,
  'total_deaths': 42,
  'total_recovered': 143,
  'active_cases': 362
}, {
  'country': 'Morocco',
  'total_cases': 516,
  'new_cases': 37,
  'total_deaths': 27,
  'new_deaths': 1,
  'total_recovered': 13,
  'active_cases': 476,
  'serious_cases': 1
}, {
  'country': 'Bahrain',
  'total_cases': 515,
  'new_cases': 16,
  'total_deaths': 4,
  'total_recovered': 279,
  'active_cases': 232,
  'serious_cases': 2
}, {
  'country': 'Algeria',
  'total_cases': 511,
  'total_deaths': 31,
  'total_recovered': 31,
  'active_cases': 449
}, {
  'country': 'Lithuania',
  'total_cases': 484,
  'new_cases': 24,
  'total_deaths': 7,
  'total_recovered': 1,
  'active_cases': 476,
  'serious_cases': 5
}, {
  'country': 'Armenia',
  'total_cases': 482,
  'new_cases': 58,
  'total_deaths': 3,
  'total_recovered': 30,
  'active_cases': 449,
  'serious_cases': 15
}, {
  'country': 'Ukraine',
  'total_cases': 480,
  'new_cases': 5,
  'total_deaths': 11,
  'new_deaths': 1,
  'total_recovered': 6,
  'active_cases': 463
}, {
  'country': 'Hungary',
  'total_cases': 447,
  'new_cases': 39,
  'total_deaths': 15,
  'new_deaths': 2,
  'total_recovered': 34,
  'active_cases': 398,
  'serious_cases': 6
}, {
  'country': 'Lebanon',
  'total_cases': 446,
  'new_cases': 8,
  'total_deaths': 11,
  'new_deaths': 1,
  'total_recovered': 32,
  'active_cases': 403,
  'serious_cases': 3
}, {
  'country': 'Latvia',
  'total_cases': 376,
  'new_cases': 29,
  'total_recovered': 1,
  'active_cases': 375,
  'serious_cases': 3
}, {
  'country': 'Bosnia and Herzegovina',
  'total_cases': 354,
  'new_cases': 31,
  'total_deaths': 8,
  'new_deaths': 2,
  'total_recovered': 17,
  'active_cases': 329,
  'serious_cases': 1
}, {
  'country': 'Bulgaria',
  'total_cases': 354,
  'new_cases': 8,
  'total_deaths': 8,
  'total_recovered': 15,
  'active_cases': 331,
  'serious_cases': 13
}, {
  'country': 'Slovakia',
  'total_cases': 336,
  'new_cases': 22,
  'total_recovered': 7,
  'active_cases': 329,
  'serious_cases': 1
}, {
  'country': 'Andorra',
  'total_cases': 334,
  'total_deaths': 6,
  'total_recovered': 6,
  'active_cases': 322,
  'serious_cases': 10
}, {
  'country': 'Costa Rica',
  'total_cases': 314,
  'total_deaths': 2,
  'total_recovered': 3,
  'active_cases': 309,
  'serious_cases': 6
}, {
  'country': 'Tunisia',
  'total_cases': 312,
  'total_deaths': 8,
  'total_recovered': 2,
  'active_cases': 302,
  'serious_cases': 10
}, {
  'country': 'Taiwan',
  'total_cases': 306,
  'new_cases': 8,
  'total_deaths': 5,
  'new_deaths': 2,
  'total_recovered': 39,
  'active_cases': 262
}, {
  'country': 'Uruguay',
  'total_cases': 304,
  'total_deaths': 1,
  'active_cases': 303,
  'serious_cases': 9
}, {
  'country': 'Kazakhstan',
  'total_cases': 294,
  'new_cases': 10,
  'total_deaths': 1,
  'total_recovered': 20,
  'active_cases': 273
}, {
  'country': 'Kuwait',
  'total_cases': 266,
  'new_cases': 11,
  'total_recovered': 72,
  'active_cases': 194,
  'serious_cases': 13
}, {
  'country': 'Moldova',
  'total_cases': 263,
  'total_deaths': 2,
  'total_recovered': 13,
  'active_cases': 248,
  'serious_cases': 33
}, {
  'country': 'North Macedonia',
  'total_cases': 259,
  'total_deaths': 6,
  'total_recovered': 3,
  'active_cases': 250,
  'serious_cases': 1
}, {
  'country': 'Jordan',
  'total_cases': 259,
  'total_deaths': 4,
  'new_deaths': 1,
  'total_recovered': 18,
  'active_cases': 237,
  'serious_cases': 3
}, {
  'country': 'San Marino',
  'total_cases': 230,
  'new_cases': 6,
  'total_deaths': 25,
  'new_deaths': 3,
  'total_recovered': 13,
  'active_cases': 192,
  'serious_cases': 16
}, {
  'country': 'Albania',
  'total_cases': 223,
  'new_cases': 11,
  'total_deaths': 11,
  'new_deaths': 1,
  'total_recovered': 44,
  'active_cases': 168,
  'serious_cases': 7
}, {
  'country': 'Burkina Faso',
  'total_cases': 222,
  'total_deaths': 12,
  'total_recovered': 23,
  'active_cases': 187
}, {
  'country': 'Cyprus',
  'total_cases': 214,
  'total_deaths': 6,
  'total_recovered': 15,
  'active_cases': 193,
  'serious_cases': 3
}, {
  'country': 'Azerbaijan',
  'total_cases': 209,
  'total_deaths': 4,
  'total_recovered': 15,
  'active_cases': 190,
  'serious_cases': 23
}, {
  'country': 'Vietnam',
  'total_cases': 203,
  'new_cases': 9,
  'total_recovered': 52,
  'active_cases': 151,
  'serious_cases': 3
}, {
  'country': 'Réunion',
  'total_cases': 183,
  'total_recovered': 1,
  'active_cases': 182
}, {
  'country': 'Oman',
  'total_cases': 179,
  'new_cases': 12,
  'total_recovered': 29,
  'active_cases': 150,
  'serious_cases': 3
}, {
  'country': 'Faeroe Islands',
  'total_cases': 168,
  'new_cases': 9,
  'total_recovered': 70,
  'active_cases': 98,
  'serious_cases': 1
}, {
  'country': 'Ivory Coast',
  'total_cases': 165,
  'total_deaths': 1,
  'total_recovered': 4,
  'active_cases': 160
}, {
  'country': 'Senegal',
  'total_cases': 162,
  'new_cases': 20,
  'total_recovered': 27,
  'active_cases': 135
}, {
  'country': 'Malta',
  'total_cases': 156,
  'new_cases': 5,
  'total_recovered': 2,
  'active_cases': 154,
  'serious_cases': 4
}, {
  'country': 'Ghana',
  'total_cases': 152,
  'total_deaths': 5,
  'total_recovered': 2,
  'active_cases': 145,
  'serious_cases': 1
}, {
  'country': 'Uzbekistan',
  'total_cases': 149,
  'new_cases': 5,
  'total_deaths': 2,
  'total_recovered': 7,
  'active_cases': 140,
  'serious_cases': 8
}, {
  'country': 'Cameroon',
  'total_cases': 139,
  'total_deaths': 6,
  'total_recovered': 5,
  'active_cases': 128
}, {
  'country': 'Cuba',
  'total_cases': 139,
  'total_deaths': 3,
  'total_recovered': 4,
  'active_cases': 132,
  'serious_cases': 2
}, {
  'country': 'Honduras',
  'total_cases': 139,
  'new_cases': 29,
  'total_deaths': 3,
  'total_recovered': 3,
  'active_cases': 133,
  'serious_cases': 4
}, {
  'country': 'Brunei ',
  'total_cases': 127,
  'new_cases': 1,
  'total_deaths': 1,
  'total_recovered': 38,
  'active_cases': 88,
  'serious_cases': 3
}, {
  'country': 'Sri Lanka',
  'total_cases': 122,
  'new_cases': 5,
  'total_deaths': 1,
  'total_recovered': 15,
  'active_cases': 106,
  'serious_cases': 5
}, {
  'country': 'Afghanistan',
  'total_cases': 120,
  'total_deaths': 4,
  'total_recovered': 2,
  'active_cases': 114
}, {
  'country': 'Venezuela',
  'total_cases': 119,
  'total_deaths': 3,
  'total_recovered': 39,
  'active_cases': 77,
  'serious_cases': 6
}, {
  'country': 'Palestine',
  'total_cases': 115,
  'new_cases': 6,
  'total_deaths': 1,
  'total_recovered': 18,
  'active_cases': 96
}, {
  'country': 'Nigeria',
  'total_cases': 111,
  'total_deaths': 1,
  'total_recovered': 3,
  'active_cases': 107
}, {
  'country': 'Mauritius',
  'total_cases': 110,
  'new_cases': 3,
  'total_deaths': 3,
  'active_cases': 107,
  'serious_cases': 1
}, {
  'country': 'Channel Islands',
  'total_cases': 108,
  'total_deaths': 2,
  'active_cases': 106
}, {
  'country': 'Cambodia',
  'total_cases': 107,
  'new_cases': 4,
  'total_recovered': 21,
  'active_cases': 86,
  'serious_cases': 1
}, {
  'country': 'Guadeloupe',
  'total_cases': 106,
  'total_deaths': 4,
  'total_recovered': 17,
  'active_cases': 85,
  'serious_cases': 10
}, {
  'country': 'Georgia',
  'total_cases': 98,
  'new_cases': 7,
  'total_recovered': 18,
  'active_cases': 80,
  'serious_cases': 1
}, {
  'country': 'Bolivia',
  'total_cases': 96,
  'new_cases': 15,
  'total_deaths': 3,
  'new_deaths': 2,
  'active_cases': 93,
  'serious_cases': 3
}, {
  'country': 'Belarus',
  'total_cases': 94,
  'total_recovered': 32,
  'active_cases': 62,
  'serious_cases': 2
}, {
  'country': 'Kyrgyzstan',
  'total_cases': 94,
  'new_cases': 10,
  'active_cases': 94
}, {
  'country': 'Martinique',
  'total_cases': 93,
  'total_deaths': 1,
  'active_cases': 92,
  'serious_cases': 12
}, {
  'country': 'Montenegro',
  'total_cases': 91,
  'new_cases': 6,
  'total_deaths': 1,
  'active_cases': 90,
  'serious_cases': 1
}, {
  'country': 'Mayotte',
  'total_cases': 82,
  'new_cases': 19,
  'total_recovered': 10,
  'active_cases': 72,
  'serious_cases': 3
}, {
  'country': 'DRC',
  'total_cases': 81,
  'total_deaths': 8,
  'total_recovered': 2,
  'active_cases': 71
}, {
  'country': 'Trinidad and Tobago',
  'total_cases': 78,
  'total_deaths': 3,
  'total_recovered': 1,
  'active_cases': 74
}, {
  'country': 'Rwanda',
  'total_cases': 70,
  'active_cases': 70
}, {
  'country': 'Gibraltar',
  'total_cases': 65,
  'total_recovered': 14,
  'active_cases': 51
}, {
  'country': 'Paraguay',
  'total_cases': 64,
  'new_cases': 5,
  'total_deaths': 3,
  'total_recovered': 1,
  'active_cases': 60,
  'serious_cases': 3
}, {
  'country': 'Liechtenstein',
  'total_cases': 62,
  'new_cases': 6,
  'active_cases': 62
}, {
  'country': 'Aruba',
  'total_cases': 50,
  'total_recovered': 1,
  'active_cases': 49
}, {
  'country': 'Bangladesh',
  'total_cases': 49,
  'new_cases': 1,
  'total_deaths': 5,
  'total_recovered': 19,
  'active_cases': 25,
  'serious_cases': 1
}, {
  'country': 'Monaco',
  'total_cases': 46,
  'total_deaths': 1,
  'total_recovered': 1,
  'active_cases': 44
}, {
  'country': 'Isle of Man',
  'total_cases': 46,
  'new_cases': 4,
  'active_cases': 46
}, {
  'country': 'French Guiana',
  'total_cases': 43,
  'total_recovered': 6,
  'active_cases': 37
}, {
  'country': 'Kenya',
  'total_cases': 42,
  'total_deaths': 1,
  'total_recovered': 1,
  'active_cases': 40,
  'serious_cases': 2
}, {
  'country': 'Madagascar',
  'total_cases': 39,
  'active_cases': 39
}, {
  'country': 'Macao',
  'total_cases': 38,
  'new_cases': 1,
  'total_recovered': 10,
  'active_cases': 28
}, {
  'country': 'French Polynesia',
  'total_cases': 35,
  'new_cases': 5,
  'active_cases': 35,
  'serious_cases': 2
}, {
  'country': 'Guatemala',
  'total_cases': 34,
  'total_deaths': 1,
  'total_recovered': 10,
  'active_cases': 23,
  'serious_cases': 1
}, {
  'country': 'Barbados',
  'total_cases': 33,
  'active_cases': 33
}, {
  'country': 'Uganda',
  'total_cases': 33,
  'active_cases': 33
}, {
  'country': 'Jamaica',
  'total_cases': 32,
  'total_deaths': 1,
  'total_recovered': 2,
  'active_cases': 29
}, {
  'country': 'Togo',
  'total_cases': 30,
  'new_cases': 5,
  'total_deaths': 1,
  'total_recovered': 1,
  'active_cases': 28
}, {
  'country': 'El Salvador',
  'total_cases': 30,
  'new_cases': 6,
  'active_cases': 30
}, {
  'country': 'Zambia',
  'total_cases': 29,
  'active_cases': 29
}, {
  'country': 'Mali',
  'total_cases': 25,
  'new_cases': 7,
  'total_deaths': 2,
  'new_deaths': 1,
  'active_cases': 23
}, {
  'country': 'Ethiopia',
  'total_cases': 23,
  'new_cases': 2,
  'total_recovered': 1,
  'active_cases': 22
}, {
  'country': 'Niger',
  'total_cases': 22,
  'new_cases': 4,
  'total_deaths': 3,
  'new_deaths': 2,
  'active_cases': 19
}, {
  'country': 'Bermuda',
  'total_cases': 22,
  'total_recovered': 2,
  'active_cases': 20
}, {
  'country': 'Congo',
  'total_cases': 19,
  'active_cases': 19
}, {
  'country': 'Tanzania',
  'total_cases': 19,
  'new_cases': 5,
  'total_recovered': 1,
  'active_cases': 18
}, {
  'country': 'Djibouti',
  'total_cases': 18,
  'active_cases': 18
}, {
  'country': 'Maldives',
  'total_cases': 17,
  'total_recovered': 13,
  'active_cases': 4
}, {
  'country': 'Guinea',
  'total_cases': 16,
  'active_cases': 16
}, {
  'country': 'Haiti',
  'total_cases': 15,
  'total_recovered': 1,
  'active_cases': 14
}, {
  'country': 'New Caledonia',
  'total_cases': 15,
  'active_cases': 15
}, {
  'country': 'Bahamas',
  'total_cases': 14,
  'total_recovered': 1,
  'active_cases': 13
}, {
  'country': 'Cayman Islands',
  'total_cases': 12,
  'total_deaths': 1,
  'active_cases': 11
}, {
  'country': 'Equatorial Guinea',
  'total_cases': 12,
  'active_cases': 12
}, {
  'country': 'Eritrea',
  'total_cases': 12,
  'active_cases': 12
}, {
  'country': 'Mongolia',
  'total_cases': 12,
  'total_recovered': 2,
  'active_cases': 10
}, {
  'country': 'Dominica',
  'total_cases': 11,
  'active_cases': 11
}, {
  'country': 'Namibia',
  'total_cases': 11,
  'total_recovered': 2,
  'active_cases': 9
}, {
  'country': 'Saint Martin',
  'total_cases': 11,
  'active_cases': 11
}, {
  'country': 'Greenland',
  'total_cases': 10,
  'total_recovered': 2,
  'active_cases': 8
}, {
  'country': 'Myanmar',
  'total_cases': 10,
  'active_cases': 10
}, {
  'country': 'Syria',
  'total_cases': 9,
  'total_deaths': 1,
  'active_cases': 8
}, {
  'country': 'Grenada',
  'total_cases': 9,
  'active_cases': 9
}, {
  'country': 'Saint Lucia',
  'total_cases': 9,
  'total_recovered': 1,
  'active_cases': 8
}, {
  'country': 'Eswatini',
  'total_cases': 9,
  'active_cases': 9
}, {
  'country': 'Curaçao',
  'total_cases': 8,
  'total_deaths': 1,
  'total_recovered': 2,
  'active_cases': 5
}, {
  'country': 'Guyana',
  'total_cases': 8,
  'total_deaths': 1,
  'active_cases': 7
}, {
  'country': 'Laos',
  'total_cases': 8,
  'active_cases': 8
}, {
  'country': 'Libya',
  'total_cases': 8,
  'active_cases': 8
}, {
  'country': 'Mozambique',
  'total_cases': 8,
  'active_cases': 8
}, {
  'country': 'Seychelles',
  'total_cases': 8,
  'active_cases': 8
}, {
  'country': 'Suriname',
  'total_cases': 8,
  'active_cases': 8
}, {
  'country': 'Angola',
  'total_cases': 7,
  'total_deaths': 2,
  'active_cases': 5
}, {
  'country': 'Gabon',
  'total_cases': 7,
  'total_deaths': 1,
  'active_cases': 6
}, {
  'country': 'Zimbabwe',
  'total_cases': 7,
  'total_deaths': 1,
  'active_cases': 6
}, {
  'country': 'Antigua and Barbuda',
  'total_cases': 7,
  'active_cases': 7
}, {
  'country': 'Saint Kitts and Nevis',
  'total_cases': 7,
  'new_cases': 5,
  'active_cases': 7
}, {
  'country': 'Sudan',
  'total_cases': 6,
  'total_deaths': 2,
  'new_deaths': 1,
  'active_cases': 4
}, {
  'country': 'Cabo Verde',
  'total_cases': 6,
  'total_deaths': 1,
  'active_cases': 5
}, {
  'country': 'Benin',
  'total_cases': 6,
  'active_cases': 6
}, {
  'country': 'Vatican City',
  'total_cases': 6,
  'active_cases': 6
}, {
  'country': 'Sint Maarten',
  'total_cases': 6,
  'active_cases': 6
}, {
  'country': 'Nepal',
  'total_cases': 5,
  'total_recovered': 1,
  'active_cases': 4
}, {
  'country': 'Fiji',
  'total_cases': 5,
  'active_cases': 5
}, {
  'country': 'Mauritania',
  'total_cases': 5,
  'total_recovered': 2,
  'active_cases': 3
}, {
  'country': 'Montserrat',
  'total_cases': 5,
  'active_cases': 5
}, {
  'country': 'St. Barth',
  'total_cases': 5,
  'active_cases': 5
}, {
  'country': 'Gambia',
  'total_cases': 4,
  'total_deaths': 1,
  'active_cases': 3
}, {
  'country': 'Nicaragua',
  'total_cases': 4,
  'total_deaths': 1,
  'active_cases': 3
}, {
  'country': 'Bhutan',
  'total_cases': 4,
  'active_cases': 4
}, {
  'country': 'Turks and Caicos',
  'total_cases': 4,
  'active_cases': 4
}, {
  'country': 'CAR',
  'total_cases': 3,
  'active_cases': 3
}, {
  'country': 'Chad',
  'total_cases': 3,
  'active_cases': 3
}, {
  'country': 'Liberia',
  'total_cases': 3,
  'active_cases': 3
}, {
  'country': 'Somalia',
  'total_cases': 3,
  'active_cases': 3
}, {
  'country': 'MS Zaandam',
  'total_cases': 2,
  'active_cases': 2
}, {
  'country': 'Anguilla',
  'total_cases': 2,
  'active_cases': 2
}, {
  'country': 'Belize',
  'total_cases': 2,
  'active_cases': 2
}, {
  'country': 'British Virgin Islands',
  'total_cases': 2,
  'active_cases': 2
}, {
  'country': 'Guinea-Bissau',
  'total_cases': 2,
  'active_cases': 2
}, {
  'country': 'Papua New Guinea',
  'total_cases': 1,
  'active_cases': 1
}, {
  'country': 'Timor-Leste',
  'total_cases': 1,
  'active_cases': 1
}, {
  'country': 'China',
  'total_cases': 81470,
  'new_cases': 31,
  'total_deaths': 3304,
  'new_deaths': 4,
  'total_recovered': 75700,
  'active_cases': 2466,
  'serious_cases': 633
}, {
  'country': 'Total:',
  'total_cases': 737204,
  'new_cases': 14845,
  'total_deaths': 34959,
  'new_deaths': 993,
  'total_recovered': 156263,
  'active_cases': 545982,
  'serious_cases': 28293
}]